### ISSUE TITLE
fmt gets confused with comment in function chain

### ISSUE THREAD

**Issue by nederdirk** [phpfmt/php.tools#52] opened 2015-08-04 08:34 UTC
`fmt` (on latest master, commit 04fb18feb33c75e4a0a4300de730cbfb41c593ac) indents a multi line function call wrong (too much indentation), if there is a line comment somewhere in the function chain.

Consider `wrong.php`
```php
<?php
$foo->bar(
    'aoeu'
)->
// comment
baz();
```
is formatted correctly (1 indentation level for the argument)
gets formatted to:
```php
$foo->bar(
        'aoeu'
    )->
// comment
baz();
```
(2 levels of indentation)

Whereas `correct.php`:
```php
<?php
$foo->bar(
    'aoeu'
)->
baz();
```
is not changed after the application of `fmt`

**Comment by dericofilho** [comment] 2015-08-04 08:42
@nederdirk I am sorry for this bug. I shall fix it ASAP.

**Comment by nederdirk** [comment] 2015-08-04 08:45
Thank you for your quick response, I'm working on a PR with test cases right now

**Comment by dericofilho** [comment] 2015-08-04 08:51
@nederdirk I was double checking, I really think it is working as intended. Because when you have an extra T_OBJECT_OPERATOR, the right thing to do is to increase indentation level. Thus:

```
$a->a
    ->b
```

When you have an unbalanced parentheses, it also should add an extra indentation, thus:
```
f(
    $a
);
```

If they are both merged together, they should be stacking both indentation levels.

Probably, you want to replace in your calls `ReindentAndAlignObjOps` with `ReindentAlignObjOps` which shall do exactly what you just asked.

**Comment by dericofilho** [comment] 2015-08-04 08:54
@nederdirk I was double checking, I really think it is working as intended. Because when you have an extra T_OBJECT_OPERATOR, the right thing to do is to increase indentation level. Thus:

```
$a->a
    ->b
```

When you have an unbalanced parentheses, it also should add an extra indentation, thus:
```
f(
    $a
);
```

If they are both merged together, they should be stacking both indentation levels.

Probably, you want to replace in your calls `ReindentAndAlignObjOps` with `ReindentObjOps` which shall do exactly what you just asked.

**Comment by nederdirk** [comment] 2015-08-04 08:59
Hmm, in that case `correct.php` would be indented wrong. With what you just described the call to `baz()` should be indented. (Personally I think that's not the right thing to do, but that's a matter of style)

**Comment by dericofilho** [comment] 2015-08-04 09:03
@nederdirk Now I am confused. :) I really don't know.

**Comment by dericofilho** [comment] 2015-08-04 09:05
This is a clearer snippet to understand the problem.
```
<?php
$foo->bar(
	'aoeu'
)->
baz();

$foo->bar(
	'aoeu'
)
->baz();
```

**Comment by dericofilho** [comment] 2015-08-04 09:07
This Pass is meant to fix the indentation and alignment of T_OBJECT_OPERATOR placed in beginning of lines, not as the last thing in the line. I really need to understand why would someone put the T_OBJECT_OPERATOR as the last thing in line.

**Comment by nederdirk** [comment] 2015-08-04 09:12
So am I, I would expect (as does our phpcs checker) this:
```php
$foo->bar( /* base indentation level 0, but unbalanced parenthesis, increase indentation by 1 level */
    'aoeu'
) /* parentheses balanced again, decrease indentation level */
->baz(); /* continue on base indentation level */
```

I'm not sure if the placement of T_OBJECT_OPERATOR is really relevant in this issue. If it matters if the T_OBJECT_OPERATOR token is at the beginning or at the end of the line, I would expect `phpfmt` to fix that. (Although PSR-2 doesn't specify where the T_OBJECT_OPERATOR should go)

**Comment by dericofilho** [comment] 2015-08-04 09:12
This, is already working with `ReindentObjOp`
```php
$foo->bar( /* base indentation level 0, but unbalanced parenthesis, increase indentation by 1 level */
    'aoeu'
) /* parentheses balanced again, decrease indentation level */
->baz(); /* continue on base indentation level */
```

**Comment by nederdirk** [comment] 2015-08-04 09:13
Yes, and that is exactly what I'm pointing at. The normal situation works, but with the line comment it seems to break (at least vexes our PSR-2 checker)

**Comment by dericofilho** [comment] 2015-08-04 09:16
OK... Now it is much clearer for me. What's the difference between:

```
$foo->bar(
	'aoeu'
)
        ->baz();
```

And
```
$foo->bar('aoeu')
        ->baz();
```

So I strongly believe phpfmt is not broken. Call chains have an indentation level of their own.

**Comment by nederdirk** [comment] 2015-08-04 09:18
Then I still don't understand why the output of `wrong.php` and `correct.php` would be so different. Especially because the line comment makes no intuitive difference.

**Comment by dericofilho** [comment] 2015-08-04 09:19
Uhm... I see your point. I will change the fixer to ensure comments do not interfere with indentation levels.

**Comment by dericofilho** [comment] 2015-08-04 09:24
@nederdirk please, upgrade to https://github.com/phpfmt/php.tools/commit/2fd1bc67e3e4f021024885c497557b8cbbdd2f0f

**Closed** 2015-08-05 07:34 UTC
Labels: waiting feedback
